#############################################################################
# Makefile for building: libEmptyQT.a
# Generated by qmake (2.01a) (Qt 4.8.6) on: Mon Sep 26 19:50:34 2016
# Project:  EmptyQT.pro
# Template: lib
# Command: /usr/lib/i386-linux-gnu/qt4/bin/qmake -o Makefile EmptyQT.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -O2 -fPIC -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -O2 -fPIC -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++ -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtGui -I/usr/include/qt4 -I.
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/lib/i386-linux-gnu/qt4/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = emptyqtsrc.cpp \
		cmainwindow.cpp \
		mainwindow.cpp \
		thumbnildialog.cpp \
		stackeddialog.cpp \
		fullviewdlg.cpp \
		window.cpp moc_mainwindow.cpp \
		moc_cmainwindow.cpp \
		moc_thumbnildialog.cpp \
		moc_stackeddialog.cpp \
		moc_fullviewdlg.cpp \
		moc_window.cpp
OBJECTS       = emptyqtsrc.o \
		cmainwindow.o \
		mainwindow.o \
		thumbnildialog.o \
		stackeddialog.o \
		fullviewdlg.o \
		window.o \
		moc_mainwindow.o \
		moc_cmainwindow.o \
		moc_thumbnildialog.o \
		moc_stackeddialog.o \
		moc_fullviewdlg.o \
		moc_window.o
DIST          = /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/staticlib.prf \
		/usr/share/qt4/mkspecs/features/static.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		EmptyQT.pro
QMAKE_TARGET  = EmptyQT
DESTDIR       = 
TARGET        = libEmptyQT.a

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET) 

staticlib: $(TARGET)

$(TARGET):  $(OBJECTS) $(OBJCOMP) 
	-$(DEL_FILE) $(TARGET)
	$(AR) $(TARGET) $(OBJECTS)


Makefile: EmptyQT.pro  /usr/share/qt4/mkspecs/linux-g++/qmake.conf /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/staticlib.prf \
		/usr/share/qt4/mkspecs/features/static.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		/usr/lib/i386-linux-gnu/libQtGui.prl \
		/usr/lib/i386-linux-gnu/libQtCore.prl
	$(QMAKE) -o Makefile EmptyQT.pro
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/common/gcc-base.conf:
/usr/share/qt4/mkspecs/common/gcc-base-unix.conf:
/usr/share/qt4/mkspecs/common/g++-base.conf:
/usr/share/qt4/mkspecs/common/g++-unix.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/release.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/staticlib.prf:
/usr/share/qt4/mkspecs/features/static.prf:
/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/share/qt4/mkspecs/features/include_source_dir.prf:
/usr/lib/i386-linux-gnu/libQtGui.prl:
/usr/lib/i386-linux-gnu/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -o Makefile EmptyQT.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/EmptyQT1.0.0 || $(MKDIR) .tmp/EmptyQT1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/EmptyQT1.0.0/ && $(COPY_FILE) --parents mainwindow.h cmainwindow.h thumbnildialog.h stackeddialog.h fullviewdlg.h window.h .tmp/EmptyQT1.0.0/ && $(COPY_FILE) --parents emptyqtsrc.cpp cmainwindow.cpp mainwindow.cpp thumbnildialog.cpp stackeddialog.cpp fullviewdlg.cpp window.cpp .tmp/EmptyQT1.0.0/ && (cd `dirname .tmp/EmptyQT1.0.0` && $(TAR) EmptyQT1.0.0.tar EmptyQT1.0.0 && $(COMPRESS) EmptyQT1.0.0.tar) && $(MOVE) `dirname .tmp/EmptyQT1.0.0`/EmptyQT1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/EmptyQT1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_mainwindow.cpp moc_cmainwindow.cpp moc_thumbnildialog.cpp moc_stackeddialog.cpp moc_fullviewdlg.cpp moc_window.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_mainwindow.cpp moc_cmainwindow.cpp moc_thumbnildialog.cpp moc_stackeddialog.cpp moc_fullviewdlg.cpp moc_window.cpp
moc_mainwindow.cpp: mainwindow.h
	/usr/lib/i386-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) mainwindow.h -o moc_mainwindow.cpp

moc_cmainwindow.cpp: cmainwindow.h
	/usr/lib/i386-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) cmainwindow.h -o moc_cmainwindow.cpp

moc_thumbnildialog.cpp: thumbnildialog.h
	/usr/lib/i386-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) thumbnildialog.h -o moc_thumbnildialog.cpp

moc_stackeddialog.cpp: stackeddialog.h
	/usr/lib/i386-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) stackeddialog.h -o moc_stackeddialog.cpp

moc_fullviewdlg.cpp: fullviewdlg.h
	/usr/lib/i386-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) fullviewdlg.h -o moc_fullviewdlg.cpp

moc_window.cpp: window.h
	/usr/lib/i386-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) window.h -o moc_window.cpp

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean 

####### Compile

emptyqtsrc.o: emptyqtsrc.cpp window.h \
		mainwindow.h \
		emptyqtsrc.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o emptyqtsrc.o emptyqtsrc.cpp

cmainwindow.o: cmainwindow.cpp cmainwindow.h \
		stackeddialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o cmainwindow.o cmainwindow.cpp

mainwindow.o: mainwindow.cpp mainwindow.h \
		stackeddialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o mainwindow.cpp

thumbnildialog.o: thumbnildialog.cpp thumbnildialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o thumbnildialog.o thumbnildialog.cpp

stackeddialog.o: stackeddialog.cpp stackeddialog.h \
		thumbnildialog.h \
		fullviewdlg.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o stackeddialog.o stackeddialog.cpp

fullviewdlg.o: fullviewdlg.cpp fullviewdlg.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o fullviewdlg.o fullviewdlg.cpp

window.o: window.cpp window.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o window.o window.cpp

moc_mainwindow.o: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o moc_mainwindow.cpp

moc_cmainwindow.o: moc_cmainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_cmainwindow.o moc_cmainwindow.cpp

moc_thumbnildialog.o: moc_thumbnildialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_thumbnildialog.o moc_thumbnildialog.cpp

moc_stackeddialog.o: moc_stackeddialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_stackeddialog.o moc_stackeddialog.cpp

moc_fullviewdlg.o: moc_fullviewdlg.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_fullviewdlg.o moc_fullviewdlg.cpp

moc_window.o: moc_window.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_window.o moc_window.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

