######################################################################
# Automatically generated by qmake (2.01a) Thu Sep 22 21:11:46 2016
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += . .
INCLUDEPATH += .

# Input
HEADERS += emptyqtsrc.h window.h
SOURCES += emptyqtsrc.cpp window.cpp
